In [1]:

from google.colab import files

uploaded = files.upload()

Saving hello_this_is_python.wav to hello_this_is_python.wav


In [2]:
import numpy as np

In [3]:
a = ["0", 1, "two", "3", 4]

print(a)
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

['0', 1, 'two', '3', 4]
0
1
two
3
4


In [4]:
import numpy as np

a = np.array([0, 1, 2, 3, 4])

print(a)

[0 1 2 3 4]


In [5]:
a = np.array([0, 1, 2, 3, 4])

print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

0
1
2
3
4


In [6]:
a = np.array([0, 1, 2, 3, 4])

print(type(a))

<class 'numpy.ndarray'>


In [7]:
a = np.array([0, 1, 2, 3, 4])

print(a.dtype)

int64


In [8]:
a = np.array([0, 1, 2, 3, 4])

print("Size:", a.size)
print("Dimension:", a.ndim)
print("Shape:", a.shape)

Size: 5
Dimension: 1
Shape: (5,)


In [9]:
b = np.array([3.1, 11.02, 6.2, 213.2, 5.2])

print(b)
print(type(b))
print(b.dtype)

[  3.1   11.02   6.2  213.2    5.2 ]
<class 'numpy.ndarray'>
float64


In [10]:
c = np.array([20, 1, 2, 3, 4])

c[0] = 100

print(c)

[100   1   2   3   4]


In [11]:
c = np.array([20, 1, 2, 3, 4])

c[0] = 100
c[4] = 0

print(c)

[100   1   2   3   0]


In [12]:
c = np.array([100, 1, 2, 3, 4])

print(c[1:4])

[1 2 3]


In [13]:
c = np.array([100, 1, 2, 3, 4])

c[3:5] = [300, 400]

print(c)

[100   1   2 300 400]


In [14]:
u = np.array([1, 0])
v = np.array([0, 1])

z = u + v

print(z)

[1 1]


In [15]:
u = [1, 0]
v = [0, 1]

z = []

for n, m in zip(u, v):
    z.append(n + m)

print(z)

[1, 1]


In [16]:
u = [1, 0]
v = [0, 1]

z = []

for n, m in zip(u, v):
    z.append(n - m)

print(z)

[1, -1]


In [17]:
y = np.array([1, 2])

z = 2 * y

print(z)

[2 4]


In [18]:
y = [1, 2]

z = []

for n in y:
    z.append(2 * n)

print(z)

[2, 4]


In [19]:
u = np.array([1, 2])
v = np.array([3, 2])

z = u * v

print(z)

[3 4]
