In [ ]:
#Demonstrate NumPy array creation, indexing, slicing, reshaping, broadcasting and mathematical operations on multidimensionalarrays.

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Array:")
print(a)

Array:
[[1 2 3]
 [4 5 6]]


In [3]:
print("Element at row 1, column 2:", a[0, 1])

Element at row 1, column 2: 2


In [4]:
print("First row:", a[0, :])
print("First two columns:")
print(a[:, 0:2])

First row: [1 2 3]
First two columns:
[[1 2]
 [4 5]]


In [6]:
b = np.array([1, 2, 3, 4, 5, 6])
c = b.reshape(2, 3)

print("Reshaped array:")
print(c)

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [7]:
print("Array + 10:")
print(a + 10)

Array + 10:
[[11 12 13]
 [14 15 16]]


In [8]:
print("Addition:")
print(a + 2)

Addition:
[[3 4 5]
 [6 7 8]]


In [9]:
print("Multiplication:")
print(a * 2)

Multiplication:
[[ 2  4  6]
 [ 8 10 12]]


In [10]:
print("Square:")
print(a ** 2)

Square:
[[ 1  4  9]
 [16 25 36]]


In [11]:
print("Sum:", np.sum(a))
print("Maximum:", np.max(a))
print("Minimum:", np.min(a))

Sum: 21
Maximum: 6
Minimum: 1
